console_title_template = '{{.PWD}}'
version = 3
final_space = true

[secondary_prompt]
  template = ' >> '
  foreground = 'white'
  background = 'transparent'

[transient_prompt]
  template = '> '
  background = 'transparent'
  foreground_templates = ['{{if gt .Code 0}}red{{end}}', '{{if eq .Code 0}}white{{end}}']

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    style = 'plain'
    template = '(Root) '
    type = 'root'

  [[blocks.segments]]
    style = 'plain'
    template = '{{ if .SSHSession }}(SSH) {{ end }}'
    type = 'session'

  [[blocks.segments]]
    style = 'plain'
    foreground = 'white'
    type = 'path'

    [blocks.segments.properties]
      style = 'powerlevel'

  [[blocks.segments]]
    style = 'plain'
    template = '>'
    foreground = 'white'
    type = 'text'
