"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
final_space = true
version = 2

[[blocks]]
type = "prompt"
alignment = "left"
newline = true

  [[blocks.segments]]
  type = "root"
  style = "plain"
  template = "(󱐋) "

  [[blocks.segments]]
  type = "session"
  style = "plain"
  template = "{{ if .SSHSession }}() {{ end }}"

  [[blocks.segments]]
  type = "path"
  style = "plain"
  foreground = "white"

    [blocks.segments.properties]
    style = "powerlevel"

  [[blocks.segments]]
  type = "text"
  foreground = "white"
  style = "plain"
  template = "❯"

[transient_prompt]
  foreground_templates = [
    "{{if gt .Code 0}}red{{end}}",
    "{{if eq .Code 0}}white{{end}}",
  ]
  background = 'transparent'
  template = '❯ '


[secondary_prompt]
  foreground = 'white'
  background = 'transparent'
  template = ' ❯❯ '
